### PR TITLE
Improve/designer news example

### PR DESCRIPTION
**Pull request by RamonGilabert**
I guess we could do some more refactor and it doesn't add a big feature to the code, but it works! :dancers:

### CODE REVIEW

**Comment by NSElvis** [comment]
I had a slightly different idea of this, I'll make a branch and send you a PR to your PR.

Looks awesome anyway :heart:

**Comment by NSElvis** [comment]
I can't get the comments to show, it says 

```
2015-03-27 07:44:43.809 DesignerNews[6416:120824] *** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
```

**Comment by RamonGilabert** [comment]
Oh, I fixed that... I'll try it again... :/

**Comment by RamonGilabert** [comment]
Fixed two problems, I guess @NSElvis that, if we fix the problem you put today in Property Mappers, then we could do it the other way, also, we could add a label with the author and the date into the comments, this was just a quick way to do it! :snail:

**Comment by NSElvis** [comment]
Damn, still get the error

**Pull request merged**
