### PR TITLE
Added feature to sync relationships with only ID

### LINKED ISSUE #140: Sync relationships by only providing the id
Today to sync a relationship you need the full JSON object. This is because Sync prefers to make sure that if the object isn't found in Core Data, it will just add it to Core Data and link it to the necessary objects.

For example if you had a list of projects that had a category inside (Project -- to one --> Category) the JSON should look like this:

```json
{
    "id":12345,
    "name":"My Project",
    "category":{
       "id":12345,
       "name":"My category"
    }
}
```

But if you are super sure that the category already has been inserted in Core Data and is not going to be removed while the sync operation is in progress you should be able to just send.

```json
{
    "id":12345,
    "name":"My Project",
    "category_id":12345
}
```

The requirement of the full JSON object from Sync comes from the fact that it ensures that the required category object will exist at all times, sadly not all the APIs work this way and they choose to remove this since it causes data repetition.

Related to #139 and #64.

### PR DESCRIPTION
**Pull request by tpmullan**
Here is a proposed change that fixes #140 

An object that is referenced with "{model}_id"  will be related if it exists in Core Data

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @tpmullan!

Thanks for your PR. I was thinking on having `hyper.justForeignKey : YES` because it doesn't break backwards compatibility, meanwhile using `{model}_id` will break some things that have already worked for some people.

**Comment by 3lvis** [comment]
This is how we added primary key support to Core Data

https://github.com/hyperoslo/NSEntityDescription-SYNCPrimaryKey

**Comment by tpmullan** [comment]
Just curious, what would this break?  It should only add the relationship if the other model exists, and if for some reason the same key was present in Core Data it should still sync the field.  The main reason I went with this representation was because our backend is in Ruby on Rails and this is how relationships are present in json by default.  I see the advantage in also supporting the feature the way you describe, but why not both?

**Comment by 3lvis** [comment]
@tpmullan makes sense :) I'll add a few test cases, and try this on master.

**Comment by 3lvis** [comment]
Thanks :heart:

**Pull request merged**
