### PR TITLE
[Demo purposes]: Patient 

### PR DESCRIPTION
**Pull request by 3lvis**
Sync is working fine, the only thing that seems to be missing is `Fitness`, `Alcohol` and `Weight` printing their measures. This is because `hyp_dictionary` is not recursive, it just prints `childs` up to one level. I opened an issue for that, but that was expected behaviour. https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/82

screen shot 2015-09-28 at 11 30 35

### CODE REVIEW

**Comment by 3lvis** [comment]
Core Data Content

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<model userDefinedModelVersionIdentifier="" type="com.apple.IDECoreDataModeler.DataModel" documentVersion="1.0" lastSavedToolsVersion="8195" systemVersion="14F27" minimumToolsVersion="Automatic">
    <entity name="Alcohol" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="measure" optional="YES" maxCount="1" deletionRule="Cascade" destinationEntity="Measure" inverseName="alcohol" inverseEntity="Measure" syncable="YES"/>
        <relationship name="patient" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Patient" inverseName="alcohols" inverseEntity="Patient" syncable="YES"/>
    </entity>
    <entity name="Baseline" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="patient" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Patient" inverseName="baselines" inverseEntity="Patient" syncable="YES"/>
    </entity>
    <entity name="Fitness" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="measure" optional="YES" maxCount="1" deletionRule="Cascade" destinationEntity="Measure" inverseName="fitness" inverseEntity="Measure" syncable="YES"/>
        <relationship name="patient" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Patient" inverseName="fitnesses" inverseEntity="Patient" syncable="YES"/>
    </entity>
    <entity name="Measure" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="alcohol" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Alcohol" inverseName="measure" inverseEntity="Alcohol" syncable="YES"/>
        <relationship name="fitness" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Fitness" inverseName="measure" inverseEntity="Fitness" syncable="YES"/>
        <relationship name="weight" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Weight" inverseName="measure" inverseEntity="Weight" syncable="YES"/>
    </entity>
    <entity name="Patient" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="alcohols" optional="YES" toMany="YES" deletionRule="Cascade" destinationEntity="Alcohol" inverseName="patient" inverseEntity="Alcohol" syncable="YES"/>
        <relationship name="baselines" optional="YES" toMany="YES" deletionRule="Cascade" destinationEntity="Baseline" inverseName="patient" inverseEntity="Baseline" syncable="YES"/>
        <relationship name="fitnesses" optional="YES" toMany="YES" deletionRule="Cascade" destinationEntity="Fitness" inverseName="patient" inverseEntity="Fitness" syncable="YES"/>
        <relationship name="weights" optional="YES" toMany="YES" deletionRule="Cascade" destinationEntity="Weight" inverseName="patient" inverseEntity="Weight" syncable="YES"/>
    </entity>
    <entity name="Weight" syncable="YES">
        <attribute name="remoteID" optional="YES" attributeType="Integer 32" defaultValueString="0" syncable="YES"/>
        <attribute name="text" optional="YES" attributeType="String" syncable="YES"/>
        <relationship name="measure" optional="YES" maxCount="1" deletionRule="Cascade" destinationEntity="Measure" inverseName="weight" inverseEntity="Measure" syncable="YES"/>
        <relationship name="patient" optional="YES" maxCount="1" deletionRule="Nullify" destinationEntity="Patient" inverseName="weights" inverseEntity="Patient" syncable="YES"/>
    </entity>
    <elements>
        <element name="Baseline" positionX="-270" positionY="-63" width="128" height="88"/>
        <element name="Patient" positionX="-9" positionY="-63" width="128" height="133"/>
        <element name="Alcohol" positionX="259" positionY="-115" width="128" height="103"/>
        <element name="Fitness" positionX="261" positionY="9" width="128" height="103"/>
        <element name="Weight" positionX="232" positionY="146" width="128" height="103"/>
        <element name="Measure" positionX="574" positionY="-9" width="128" height="118"/>
    </elements>
</model>
```

**Comment by 3lvis** [comment]
```json
[
  {
    "id": 0,
    "text": "Melisa White",
    "baselines": [
      {
        "id": 0,
        "text": "Baseline 1"
      }
    ],
    "alcohols": [
      {
        "id": 0,
        "text": "Alcohol 1",
        "measure": {
          "id": 0,
          "text": "Alcohol Measure 1"
        }
      }
    ],
    "fitnesses": [
      {
        "id": 0,
        "text": "Fitness 1",
        "measure": {
          "id": 0,
          "text": "Fitness Measure 1"
        }
      }
    ],
    "weights": [
      {
        "id": 0,
        "text": "Weight 1",
        "measure": {
          "id": 0,
          "text": "Weight Measure 1"
        }
      }
    ]
  }
]
```

**Comment by 3lvis** [comment]
`hyp_dictionary`
```
    alcohols =     (
                    {
                        id = 0;
                        text = "Alcohol 1";
                    }
                    );
    baselines =     (
                     {
                         id = 0;
                         text = "Baseline 1";
                     }
                     );
    fitnesses =     (
                     {
                         id = 0;
                         text = "Fitness 1";
                     }
                     );
    id = 0;
    text = "Melisa White";
    weights =     (
                   {
                       id = 0;
                       text = "Weight 1";
                   }
                   );
```

**Comment by galinyonchev** [comment]
Hm, I just can not make it work.
Look what I do and tell me if it is correct:

1. Create DataStack:
let dataStack = DATAStack(modelName: "Model")

2. Then I fetch the Patient object:
let patient: Patient = self.fetchEntity(dataStack.mainContext)

3. After that I go with this one:
patient.hyp_dictionaryUsingRelationshipType(.Array)

And it returns only the patient object without other objects (baseline and etc.)
My objects do not have attribute "ID", is this a problem? And one more thing - I do NOT use this lines of code:

NSArray *objects = [self objectsFromJSON:@"patients.json"];
[Sync changes:objects
    inEntityNamed:@"Patient"
        dataStack:dataStack
        completion:nil];

**Comment by 3lvis** [comment]
@galinyonchev it's hard for me to tell what's exactly failing in your set up. Something tells me that the issue might be how your Core Data model is set up. If you follow what I did in the example that I've shown you, it should work with no problems.

**Pull request merged**
