### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by jgorset**
Yes.

### CODE REVIEW

**Comment by NSElvis** [comment]
https://github.com/hyperoslo/Sync/pull/27 :(

**Comment by jgorset** [comment]
Haha, oh no!

**Comment by NSElvis** [comment]
@zenangst ....

**Comment by jgorset** [comment]
I WIN

**Comment by NSElvis** [comment]
:+1:

**Comment by zenangst** [comment]
@jgorset pointed to master

**Comment by NSElvis** [comment]
Pointing to master is not better

**Comment by zenangst** [comment]
It's not?

**Comment by NSElvis** [comment]
As soon as you change one line of code the URL is no longer valid

**Comment by zenangst** [comment]
Oh... well... that's awkward.

**Comment by jgorset** [comment]
That… that's true.

**Comment by zenangst** [comment]
ron-swanson-computer-throw-out-parks-and-rec

**Comment by NSElvis** [comment]
Might be even better to point to a tag! In case you break API

https://github.com/hyperoslo/Sync/tree/0.6/Examples/AppNet

**Pull request merged**
