### PR TITLE
relationship entity name fix

### PR DESCRIPTION
**Pull request by kostiakoval**
get correct EntityName for relationship

### CODE REVIEW

**Comment by NSElvis** [comment]
@kostiakoval do you mind adding a test?

**Comment by kostiakoval** [comment]
I was thinking it would work without test. hehe I will add

**Comment by NSElvis** [comment]
@kostiakoval No, I mean a test that showed what was failing.

Like:

- Add test that fails
- Add fix
- Push

**Comment by kostiakoval** [comment]
Done. If you disable my fix, the test will crash. Why -> 
the name for the relationship in no the same as entityName: 

"parent" -> type of `Collection`
screen shot 2015-03-19 at 14 04 54
@NSElvis

**Comment by NSElvis** [comment]
Nice!

**Pull request merged**
