### PR TITLE
[WIP] add falling test for many-to-one sync

### PR DESCRIPTION
**Pull request by kostiakoval**
Unique object syncing is failing with many-to-one relationship.
See the test and new Entities in the Unique model for more information
screen shot 2015-05-15 at 14 32 24

### CODE REVIEW

**Comment by 3lvis** [comment]
Not sure if this is relevant but this model doesn't seem right.

I would do

Company -->> Deparment -->> Employee

A company has many departments.
A department has many employees.

**Comment by 3lvis** [comment]
I'm trying very hard to find an example where

Parent A -->>> Some child <<<-- Parent B

**Comment by 3lvis** [comment]
Any ideas @hyperoslo/ios ?

**Comment by kostiakoval** [comment]
and if you would like to find all people in company? In my model it is very easy.
If you would like to add projects and assign people to projects ? Wound it be 
Company ->> Department ->> Projects ->> Employee
This was you would need to change existing model and code (Departments and  Employee)

**Comment by 3lvis** [comment]
@kostiakoval That's ok.

Having that makes a lot of sense.

```
Company ->> Department ->> Projects ->> Employee
```

Just because it's difficult doesn't mean that you shouldn't do it.

**Comment by 3lvis** [comment]
I'll close it until we find a real use case, so far for me this just seems that the entities are not linked correctly.

**Pull request closed without merging**
