### PR TITLE
Improve: Core Data comments

### PR DESCRIPTION
**Pull request by 3lvis**
A Core Data approach to map comments as a relationship

---
dwqdqw

### CODE REVIEW

**Comment by NSElvis** [comment]
The main problem is that a comment in https://news.layervault.com/?format=json it doesn't have an `id` so it doesn't get mapped.

The idea is to make `body` a primary key so it gets the behavior of `id`.

**Comment by RamonGilabert** [comment]
Right, here I am, but @NSElvis you deleted the issue to support custom keys!

**Comment by NSElvis** [comment]
@RamonGilabert I removed it from PropertyMapper because it's not connected in any way, it should go here.

The issue in Sync is here => https://github.com/hyperoslo/Sync/issues/31

**Comment by NSElvis** [comment]
Still it's only showing the root comment, not the child ones

**Comment by RamonGilabert** [comment]
Looks awesome!

**Pull request merged**
