### PR TITLE
Sync parents for relationships in superentities

### PR DESCRIPTION
**Pull request by Jonge**
Note that this only supports one level of superentities. For a complete support, we should recursively search for all relationship names in superentities' superentities etc.

Also, may be a good idea to write some tests for this.

See https://github.com/hyperoslo/Sync/issues/238

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @Jonge 

Thanks a lot for this. I agree, would be great if you could add a test, or provide a model + JSON that helps reproducing this, I think I could add the unit test.

**Comment by Jonge** [comment]
Sure, on it, will add the model + JSON at least.

**Comment by Jonge** [comment]
@3lvis Added sample model, JSON and unit tests for this (single-level superentities only).

**Comment by 3lvis** [comment]
Thanks a lot for this. I'm very sorry it took this long to merge. I moved your test case here to fix the conflicts and simplified a bit the test case.

Have a fantastic week!

https://github.com/hyperoslo/Sync/pull/264

**Pull request closed without merging**
